name: Lexical Release

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  build:
    name: Linux Py13
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python -m pip install --upgrade pip build twine setuptools wheel
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
