name: Build, Test & Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.13.3
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.3"

    - name: Upgrade build tools
      run: python -m pip install --upgrade pip build pytest

    - name: Build sdist
      run: python -m build --sdist

    - name: List dist contents
      run: ls -lh dist/

    - name: Extract tarball
      run: |
        mkdir unpacked
        tar -xzf dist/*.tar.gz -C unpacked
        ls -R unpacked/

    - name: Check for expected data files
      run: |
        DATA_FILES=$(find unpacked -path "./unpacked/lexical/data/*")
        if [ -z "$DATA_FILES" ]; then
          echo "Data files missing in ./unpacked/lexical/data/"
          exit 1
        fi

    - name: Install package from unpacked source
      run: pip install ./unpacked/*

    - name: Run CLI command
      run: echo "hello" | lexical --stdin

    # - name: Run tests with pytest
    #   run: pytest tests/

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build-test
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #
  #   steps:
  #   - uses: actions/checkout@v4
  #
  #   - name: Set up Python 3.13.3
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: "3.13.3"
  #
  #   - name: Upgrade build tools
  #     run: python -m pip install --upgrade pip build twine
  #
  #   - name: Build distributions
  #     run: python -m build
  #
  #   - name: Publish to PyPI
  #     env:
  #       TWINE_USERNAME: __token__
  #       TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
  #     run: twine upload dist/*
